config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def index
        @blogs = Blog.all
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.new(blog_params)
        if @blog.save
            redirect_to blogs_url
        else
            render 'new'
        end
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def edit
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
        @blog.update_attributes(blog_params)

        redirect_to blogs_url
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_url
    end

    private
        def blog_params
            params.require(:blog).permit(:title, :content)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Edit Blog</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
        <h1 class="header"><%= @blog.title %></h1>
        <div class="blog blog-detail">
            <h3 class="title"><%= @blog.title %></h3>
            <p class="content"><%= @blog.content %></p>
            <p class="time"><%= @blog.created_at %></p>
        </div>
        <div class="new-blog-form">
            <%= form_for(@blog) do |f| %>
                <span class="bold-text">Title: </span><br/><%= f.text_field :title, class: "title-input" %><br/>
                <span class="bold-text">Content: </span><br/><%= f.text_area :content, class: "text-area" %><br/>
                <%= f.submit "Update", class: "btn btn-success" %>
            <% end %>
        </div>
        <footer>
            <%= link_to 'Back', blog_path(@blog.id), class: "btn btn-primary" %>
        </footer>
    </body>
</html>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>My Blog</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
        <h1 class="header">My Blogs</h1>
        <div class="main-container">
            <div class="main">
                <div class="left-block">
                </div>
                <div class="blog-container">
                    <% @blogs = @blogs.reverse %>
                    <% @blogs.each do |blog| %>
                        <div class="blog">
                            <p class="title"><%= blog.title %></p>
                            <p class="time"><%= blog.created_at %></p>
                            <%= link_to 'Learn More', blog_path(blog), class: "btn btn-info" %>
                        </div>
                    <% end %>
                </div>
                <div class="right-block">
                </div>
            </div>
            <footer>
                <%= link_to 'New Blog', '/blogs/new', class: "btn btn-primary" %>
            </footer>
        </div>
    </body>
</html>

app/views/blogs/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>New Blog</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
        <h1 class="header">Create New Blog</h1>
        <div class="new-blog-form">
            <%= form_for(@blog) do |f| %>
                <span class="bold-text">Title: </span><br/><%= f.text_field :title, class: "title-input" %><br/>
                <span class="bold-text">Content: </span><br/><%= f.text_area :content, class: "text-area" %><br/>
                <%= f.submit "Create", class: "btn btn-success" %>
            <% end %>
        </div>
        <footer>
            <%= link_to 'Back', '/blogs', class: "btn btn-primary" %>
        </footer>
    </body>
</html>

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>My Blog</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
        <div class="blog blog-detail">
            <h1><%= @blog.title %></h1>
            <p class="content"><%= @blog.content %></p>
            <p class="time"><%= @blog.created_at %></p>
            <%= link_to 'Edit', edit_blog_path(@blog.id), class: "btn btn-primary" %>
            <%= link_to 'Delete', blog_path(@blog.id),
                method: :delete, data: {confirm: 'Are you sure to delete this blog?'},
                class: "btn btn-danger" %>
        </div>
        <footer>
            <%= link_to 'Back', '/blogs', class: "btn btn-primary" %>
        </footer>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>